### ISSUE TITLE
اضافه کردن تایپ به ریسپانس وب سرویس ها

### ISSUE THREAD

**Issue by mohsensaremi** [MehradAotp/gallery#1]
با توجه به اینکه تایپ خروجی وب سرویس ها مشخص نیست، در مستندات سووگر هیچ تایپ خروجی تعریف نشده و قابل استفاده در فرانت اند نیست.
برای بهبود مستندات سووگر ابتدا برای همه وب سرویس ها خروجی مناسب تعریف کنید و با استفاده از پکیج زیر، این تایپ ها را به طور اتوماتیک به سووگر معرفی کنید.

https://docs.nestjs.com/openapi/cli-plugin

توجه کنید که نیازی به استفاده از دکوریتور ها مانند
@ApiProperty, @ApiBody
نیست و فقط با استفاده از تعریف تایپ ها در تایپ‌اسکریپت و با استفاده از این پیلاگین  تایپ ها بطور خودکار در سووگر تولید می‌شوند

**Comment by MehradAotp** [comment]
انجام شد
