### ISSUE TITLE
بهبود تایپ عکس ها

### ISSUE THREAD

**Issue by mohsensaremi** [MehradAotp/gallery#2]
در عکس های خروجی، فیلد categories به جای اینکه دیتای دسته بندی ها را داشته باشد، فقط آیدی را نمایش می‌دهد.
تایپ خروجی عکس ها را بصورت زیر تغییر دهید:

```ts
enum StatusEnum {
pending'='pending',
approved='approved', 
rejected='rejected'
}

class CategoryDto {
id:string;
name:string;
}

class PhotoUploadedByDto {
id:string;
usernamestring;
}

class PhotoDto {
  filename: string;
  title: string;
  categories: CategoryDto[];
  description?: string;
  status: StatusEnum;
  uploadedBy: PhotoUploadedByDto;
}
```

دقت کنید که این فقط تایپ خروجی هستش و تایپ اسکیما دیتابیس درست هستش.
همچنین دقت کنید برای لود دیتای دسته بندی و کاربر آپلود کننده در وب سرویس لیست عکس ها، مشکل لود n+1 بوجود نیاید.

**Comment by MehradAotp** [comment]
انجام شد
