### ISSUE TITLE
لینک برای نمایش عکس ها

### ISSUE THREAD

**Issue by mohsensaremi** [MehradAotp/gallery#3]
برای نمایش عکس ها به مدیر و کاربر نیاز به یک URL جدید داریم
الان عکس ها ذخیره می‌شوند ولی امکان نمایش عکس وجود ندارد

نمایش عکس شروط زیر را دارد
- اگر ادمین یا کاربر صاحب عکس درخواست نمایش عکس را فرستاد، عکس در هر وضعیتی که باشد نمایش داده می‌شود
- در غیر این صورت فقط درضورتی نمایش داده می‌شود که وضعیت عکس تایید شده باشد. اگر تایید شده نبود خطای 404 می‌دهد.

برای نمایش عکس باید هدر ریسپانس را از حالت جیسون تغییر دهید. برای مثال برای نمایش عکس png از هدر زیر استفاده می‌شود:
image/png

**Comment by MehradAotp** [comment]
انجام شد.

**Comment by MehradAotp** [comment]
انجام شد.
