### ISSUE TITLE
ارسال نوتیفیکیشن به کاربر بعد از تایید یا رد عکس توسط ادمین

### ISSUE THREAD

**Issue by mohsensaremi** [MehradAotp/gallery#4]
بعد از اینکه عکس کاربر به وضعیت تایید یا رد شده درآمد، یک نوتیفیکیشن بصورت ایمیل به کاربر ارسال شود.
برای اینکار لازم است هنگام ثبت نام ایمیل کاربر نیز دریافت شود.

**Comment by MehradAotp** [comment]
انجام شد.

**Comment by mohsensaremi** [comment]
سلام
کدی که زدی درست کار میکنه ولی تمیز نیست
متد approvePhoto کارش تایید کردن عکس کاربر هستش ولی الان دوتا وظیفه براش تعریف کردی. یکی تایید عکس و یکی ارسال ایمیل

راه بهتر اینه که متد approvePhoto وظییفش فقط تایید عکس بمونه و پس از تایید عکس یک ایونتی منتشر کنه
و یجای دیگه به این ایونت گوش بدی و ایمیل رو ارسال کنی
اینطوری وظیفه هر متدی مشخصه و هر متد کار خودشو میکنه
اصطلاحا بهش میگن separation of concerns

برای اینکار داکیومنت nest رو بخون دوتا روش داره
https://docs.nestjs.com/recipes/cqrs
https://docs.nestjs.com/techniques/events

ما تو پروژه اصلی از cqrs استفاده میکنیم. بهتره تو هم از همین استفاده کنی ولی دوتاشو یاد بگیر

**Comment by MehradAotp** [comment]
لطف کردید که گفتید. انجام شدش.
