### ISSUE TITLE
Use RabbitMQ to send accepted and rejected notification

### ISSUE THREAD

**Issue by mohsensaremi** [MehradAotp/gallery#6]
طبق عکس ضمیمه، ,وقتی عکس تایید یا رد میشود، بجای پابلیش ایونت با cqrs، از rabbitmq استفاده میکنیم.

تفاوت با روش قبل این است که در این روش اپلیکیشن منتشر کننده ایوینت و اپلیکیشن گوش دهنده به ایونت جدا از هم هستند. (در روش قبلی هردو روی یک اپ بودند)
اپ master همین اپلیکیشنی هست که در این ریپازیتوری وجود دارد، برای اپ listener باید یک پروژه جدید با nest ایجاد کنید.

برای ارتباط با rabbitmq از پیکیج زیر استفاده کنید.
https://www.npmjs.com/package/@golevelup/nestjs-rabbitmq

![image](https://github.com/user-attachments/assets/621886a4-35ce-4877-81b6-cce3405f84d2)

**Comment by MehradAotp** [comment]
انجام شد.
